export const SIDEBAR = [
  {
    name: "Feed",
    route: "/",
    icon: "/assets/dashboard.svg",
  },
  {
    name: "My community",
    route: "/my-community",
    icon: "/assets/community.svg",
  },
  {
    name: "Messages",
    route: "/messages",
    icon: "/assets/message.svg",
  },
  {
    name: "Notification",
    route: "/notification",
    icon: "/assets/notification.svg",
  },
  // {
  //   name: "Explore",
  //   route: "/explore",
  //   icon: "/assets/explore.svg",
  // },
  {
    name: "Profile",
    route: "/profile",
    icon: "/assets/profile.svg",
  },
  {
    name: "Settings",
    route: "/settings",
    icon: "/assets/settings.svg",
  },
  {
    name: "Logout",
    route: "/logout",
    icon: "/assets/logout.svg",
  },
];

export const ALL_FRIENDS = [
  {
    image: "/assets/user.png",
    firstname: "Saleh",
    lastname: "James",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Bysouth",
    lastname: "Kayleigh",
    lastSeen: "2 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Phillips MP",
    lastname: "Jess",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Vjosa",
    lastname: "Albini",
    lastSeen: "8 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Saleh",
    lastname: "James",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Bysouth",
    lastname: "Kayleigh",
    lastSeen: "2 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Phillips MP",
    lastname: "Jess",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Vjosa",
    lastname: "Albini",
    lastSeen: "8 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Saleh",
    lastname: "James",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Bysouth",
    lastname: "Kayleigh",
    lastSeen: "2 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Phillips MP",
    lastname: "Jess",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Vjosa",
    lastname: "Albini",
    lastSeen: "8 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Saleh",
    lastname: "James",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Bysouth",
    lastname: "Kayleigh",
    lastSeen: "2 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Phillips MP",
    lastname: "Jess",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Vjosa",
    lastname: "Albini",
    lastSeen: "8 min",
  },
];

export const ONLINE_FRIENDS = [
  {
    image: "/assets/user.png",
    firstname: "Ortega",
    lastname: "Eduardo",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Bysouth",
    lastname: "Kayleigh",
    lastSeen: "2 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Phillips MP",
    lastname: "Jess",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Konjufca",
    lastname: "Afrim",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Ortega",
    lastname: "Eduardo",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Bysouth",
    lastname: "Kayleigh",
    lastSeen: "2 min",
  },
  {
    image: "/assets/user.png",
    firstname: "Phillips MP",
    lastname: "Jess",
    lastSeen: "now",
  },
  {
    image: "/assets/user.png",
    firstname: "Konjufca",
    lastname: "Afrim",
    lastSeen: "now",
  },
];

export const COMMUNITY_CATEGORIES = [
  {
    title: "Followers",
    amount: "52,844",
  },
  {
    title: "Following",
    amount: "2,564",
  },
  {
    title: "Recommended",
    amount: null,
  },
];

export const COMMUNITIES = [
  {
    title: "Followers",
    data: [
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
    ],
  },

  {
    title: "Following",
    data: [
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
    ],
  },

  {
    title: "Recommended",
    data: [
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: true,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
      {
        image: "/assets/user.png",
        firstname: "SkillArena",
        lastname: "Radovan",
        job: "Founder & CEO at Trophy",
        social: ["facebook", "twitter", "instagram"],
        isFollowing: false,
      },
    ],
  },
];

export const LANGUAGES = [
  { value: "af", text: "Afrikaans" },
  { value: "bn-BD", text: "Bengali" },
  { value: "ca", text: "Catalan" },
  { value: "da", text: "Danish" },
  { value: "nl", text: "Dutch" },
  { value: "en-GB", text: "English (UK)" },
  { value: "en-US", text: "English (US)" },
  { value: "es", text: "Espanol" },
  { value: "tl", text: "Tagalog" },
  { value: "fr-CA", text: "Francais (Canada)" },
  { value: "fr-FR", text: "Francais (France)" },
  { value: "de", text: "German" },
  { value: "id", text: "Indonesian" },
  { value: "ja", text: "Japanese" },
  { value: "ru", text: "Russian" },
  { value: "so", text: "Somali" },
  { value: "te", text: "Telugu" },
];

export const locales = LANGUAGES.map((language) => language.value);
